### ISSUE TITLE
can u add a userscript (similar to catchvideo) to bypass user download blocking due to ip check?

### ISSUE THREAD

**Issue by demonluo** [Rudloff/alltube#121]
after installing greasemonkey/tampermonkey + catchvideo helper userscript, i am able to bypass user download blocking due to ip check on catchvideo, i hope alltubedownload do the same since i use both... :)
http://catchvideo.net/software

eg,

some "vevo" video on youtube "block" user download due to ip check...
https://www.youtube.com/watch?v=My2FRPA3Gf8

all video on dailymotion "block" user download due to ip check...
http://www.dailymotion.com/video/x5ou9h3_mysterious-death-of-former-beauty-queen-and-actress-found-unresponsive-in-her-home_news

some "best (mp4)" video ended up on "skyfire" server on vimeo "block" user download due to ip check...
https://vimeo.com/79285546

**Comment by Rudloff** [comment]
Hello,

Catchvideo bypasses geoip restrictions, not because of their userscript but because of how they handle video extraction. But since it is not open source, I can't check how they do it.

We explored different ways to bypass these restrictions in #97 but none of them was satisfying.

On the other hand, but do provide a bookmarklet (and a [Firefox addon](https://addons.mozilla.org/en-us/firefox/addon/alltube-download/)) which is very similar to a Greasemonkey userscript.

**Comment by demonluo** [comment]
look like it's more complicated than i thought but thanks for replying...
