### ISSUE TITLE
requested format not available for france.tv site

### ISSUE THREAD

**Issue by Liandriz** [Rudloff/alltube#133]
Hi, tried to get some videos from france.tv site (former pluzz), and it didn't work from web ui,
with "ERROR: requested format not available".

But when i try directly in youtube-dl folder, for example : 
`/alltube/vendor/rg3/youtube-dl/youtube_dl # python __main__.py https://www.france.tv/france-2/nina/saison-3/305161-love-song.html`

It works, and start download the video. No other youtube-dl version on system, any hint please?

**Comment by Rudloff** [comment]
Hello,
It's because their videos are served as HLS streams and by default Alltube only supports regular HTTP downloads.
You need to enable [stream mode](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#how-do-i-enable-streaming-videos-through-the-server) for it to work.
(And you will also need [this patch](https://github.com/Rudloff/alltube/commit/095c1a92f07e3952184713865ac0924403ad053b) in order to fix an issue I just noticed.)

**Comment by Liandriz** [comment]
Thank you for your reactivity, will try it.

**Comment by Liandriz** [comment]
Thanks, all working great!
