### ISSUE TITLE
[Improvement] progress bar & format & bitrate selection

### ISSUE THREAD

**Issue by xm3n1** [Rudloff/alltube#148]
Ideas:
* add a Progress Bar for the converting/Download process.
* input option to select in which format & which bitrate the video should be converted.

**Comment by Rudloff** [comment]
* We can't really add a progress bar since the download is managed directly by the browser. It would require managing the download in JavaScript but this causes horrible performances for big files.
Ideally, the browser should display a progress bar in its download manager but this requires knowing the file size and we have no way to predict the converted file size.
* We can totally add this. Do you have specific formats in mind?

**Comment by xm3n1** [comment]
We can totally add this. Do you have specific formats in mind?
* i think about mp3, mp4, flv, wav
* custom bitrates which i think are standard on most yt converters:
````
320 kbps
256 kbps
192 kbps
128 kbps
96 kbps
64 kbps
````

**Comment by Rudloff** [comment]
This has been added to the `develop` branch.
You can enable it by adding this to your `config/config.yml` file:
```yaml
convertAdvanced: true
convertAdvancedFormats: [mp3, avi, flv, wav]
```

It will add new options on the download page that allow you to convert the video
![image](https://user-images.githubusercontent.com/840125/35361509-eb359304-0161-11e8-8ea3-5e68ac9feaa3.png)
