### ISSUE TITLE
Setting audio file size in php headers

### ISSUE THREAD

**Issue by coolguruji** [Rudloff/alltube#151]
# New issue

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
Linux
**What is your web server (Apache, IIS, etc.)?**
Apache
**What version of Alltube are you using?**
Latest
**How did you install Alltube (with Git or with a release package)?**
Git
**What version of PHP are you using?**
7.0
**What version of Python are you using?**
Python 2.6.6
**What version of youtube-dl are you using?**
2018.02.04
**Do you get any PHP-related errors in your webserver's logs?**
nope
**What is the content of your `config/config.yml` file?**
It fine. no issue
**Please provide the URL of a video that causes the issue.**
I am able to download video / audio
## Describe your issue

Hi hero,

Its me- https://github.com/Rudloff/alltube/issues/150
You've helped me a lot.

Now I just need to know one thing, how can i add file size in the php header for the audio file which is getting converted and downloaded by php chunk by chunk

      ffmpeg -i 'https://example.com/video' -f mp3 -vn pipe:1

If i try to add that manually in my script. Download gets failed after download finished and file become corrupted. 

I am trying this code to get filesize:

      function size($x) {
         $headers = @get_headers($x, 1);
         $size = $headers['Content-Length'];
     }
     $size = size($mp3path); // its a look to mp4 audio only stream url
      header('Content-length: ' . $size);
      header("Content-Range: 0-".($size-1)."/".$size);

Have need to install something like any module or i can also get the converted size from the ffmpeg.

I think this is possible because i have seen the following script. 
https://download.tubemp3convert.com/@api/button/mp3/CevxZvSJLk8
I believe this php + curl + ffmpeg  based script is fetching links from youtube and then giving instant download with ffmpeg and pipe output but he is also able to set file size.

What's your opinion?

**Comment by Rudloff** [comment]
Alltube currently does not return a `Content-Length` header.
I've tried to do this before but ffmpeg does not have an option to get the file size (probably because it is hard to predict exactly).

I guess if we used a constant bitrate, we could multiply it by the duration of the video to get the size but I'm not sure it would be exact (and if `Content-Length` is not exact, it can lead to truncated or corrupted files).

**Comment by coolguruji** [comment]
hmm, that's what happening with me buddy. Just because Content-Length is not exact file is getting corrupted.
As per your suggestion i did some quick research on web. may be you are talking about this
http://www.audiomountain.com/tech/audio-file-size.html

There is a formula suggested to by this site for calculating length of audio file.. 

Formula:-> Kbps = bits per second / 8 = Bytes per second x 60 seconds = Bytes per minute x 60 minutes = Bytes per hour.
I will do some research on it tomorrow because i need Content-Length in bytes.
Do you know how we can force ffmpeg to generate an audio file using Constant Bit-rate CBR method?
I tried this code but sometimes it generates files with 128 kbps.

    ffmpeg -i 'https://example.com/video'  -ac 2 -ab 64k -ar 44100 -f mp3 -vn pipe:1

any suggestion?

**Comment by Rudloff** [comment]
`-b:a 64k` should generate a 64kps file (see [here](https://trac.ffmpeg.org/wiki/Encode/MP3)).
However I don't think the formula will give you the exact file size since the MP3 also has a header containing some metadata.

I would still recommend not returning any `Content-Length` header until we can find a better solution, since it is better to not display the file size than having a truncated file.

**Comment by coolguruji** [comment]
hmm! I agree with you. 
This demo url will be a MP4 audio only URL.
I think this will be a correct command.

    ffmpeg -i 'https://example.com/video'  -ac 2 -b:a 64k -ab 64k -ar 44100 -f mp3 -vn pipe:1

But you generates a lot load on server. There anything that i can do to reduce the server load except caching file on server.

**Comment by Rudloff** [comment]
Encoding will always use a lot of CPU (especially since ffmpeg's MP3 encoder does not support multithreading).
The only way to use less resources is to use `-c:a copy` some ffmpeg only copies the audio stream instead of converting it. But then you can't change the audio codec or bitrate of course...

**Comment by coolguruji** [comment]
It looks like its not possible to make a mp3 file without encoding. If i try to us -c:a copy to make a mp3 file i am not getting success.
I think youtube only have webm, mp4, flv, 3gp and all of them have different codec that's why encoding is needed.
So for know i feel i cant do anything about high server load due to ffmpeg encoding :(

**Comment by Rudloff** [comment]
I'm closing this but feel free to open a new issue if you need help again.
