### ISSUE TITLE
Rename audio file

### ISSUE THREAD

**Issue by elmarcomilani** [Rudloff/alltube#160]
Hi,

is it possibile to rename the audio file to this format "Name Foo Bar.mp3" instead of "Name_Foo_Bar-ID.mp3"?

**Comment by Rudloff** [comment]
Hello,

I won't change the default because it can cause troubles on some systems (see https://github.com/rg3/youtube-dl/issues/13027). But if you host AllTube yourself you can change this behavior with a bit of work.

You can add something like this to your `config/config.yml` file:
```yaml
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
```
(The [default configuration](https://github.com/Rudloff/alltube/blob/2a3612d7ecc9da7dd1abcb364d165b58816c3bec/config/config.example.yml#L13) also has the `--restrict-filenames` parameter so you are removing it.)

Also, youtube-dl forces the `restrict-filenames` parameter if no locale is defined (https://github.com/rg3/youtube-dl/commit/e9137224b3ef638cce3dac024814397fd020f3b9), so it will only work if your PHP has the `$env['LC_ALL']` or `$env['LANG']` environment variable populated.
(This is often disabled by [`variables_order`](http://us.php.net/manual/en/ini.core.php#ini.variables-order) on recent PHP versions.)

**Comment by djradivip** [comment]
What's the best way to define the LANG variable?

I have this as variables order: variables_order = "EGPCS" in php.ini and kinda stumped. Any help appreciated.
localectl status on centos reports lang as LANG=en_US.UTF-8 , but the ENV Lang variable does not show in phpinfo.

**Comment by Rudloff** [comment]
It looks like my explanation in https://github.com/Rudloff/alltube/issues/160#issuecomment-379758956 is a bit incomplete.

Symfony uses `$_ENV` or `$_SERVER` depending on what is available: https://github.com/symfony/process/blob/afe411c2a6084f25cff55a01d0d4e1474c97ff13/Process.php#L1738
So, even `variables_order = SP` should be enough.

However, the Apache module does not seem to pass `LANG`.
You can change this behavior by editing `/etc/apache2/envvars` (on Debian, not sure if it is the same file on other distributions).
One other solution is to define it manually in the Apache configuration:
```apache
SetEnv LANG en_US.UTF-8
```

**Comment by djradivip** [comment]
Thing is that I am running OpenLiteSpeed, so I am stuck. Perhaps, I'll just setup a new Apache server running on different port and port-forward.

I tried to disable the check for the LANG variable in the YoutubeDL.py file, but ended up with empty filename in the .mp3

**Comment by Rudloff** [comment]
Well, you can always set it manually in `index.php`:
```diff
diff --git a/index.php b/index.php
index 791649b..a102c90 100644
--- a/index.php
+++ b/index.php
@@ -11,6 +11,8 @@ use Alltube\UglyRouter;
 use Alltube\ViewFactory;
 use Slim\App;
 
+$_ENV['LANG'] = 'en_US.UTF-8';
+
 if (isset($_SERVER['REQUEST_URI']) && strpos($_SERVER['REQUEST_URI'], '/index.php') !== false) {
     header('Location: '.str_ireplace('/index.php', '/', $_SERVER['REQUEST_URI']));
     die;
```

It is not very clean but it should work.
