### ISSUE TITLE
Cannot download from Bilibili

### ISSUE THREAD

**Issue by MFYDev** [Rudloff/alltube#246]
# Cannot download from Bilibili

## php7.3 nginx 1.17

**What is your operating system (Windows, Linux, OSX, etc.)?**

Ubuntu 18.04

**What is your web server (Apache, IIS, etc.)?**
Nginx
**What version of AllTube are you using?**
Latest 2019.09.12
**How did you install AllTube (with Git or with a release package)?**
release pakage
**What version of PHP are you using?**
7.3
**What version of Python are you using?**
2.7 3.6
**What version of youtube-dl are you using?**
?
**Do you get any PHP-related errors in your webserver's logs?**
no
**What is the content of your `config/config.yml` file?**
there is no such file
**Please provide the URL of a video that causes the issue.**
https://www.bilibili.com/video/av74296603
## Describe your issue
Neither mine or your demo cannot download from Bilibili, please have a check. Thanks.

**Comment by FanyangMengDev** [comment]
Hello? No one answer me?

**Comment by Rudloff** [comment]
Hello,
I am working on this project on my spare time so please don't be rude.

It looks like Bilibili requires a specific HTTP header: https://github.com/ytdl-org/youtube-dl/blob/d4f53af482cc47b0473a3576da7ad902bea4ac39/youtube_dl/extractor/bilibili.py#L182
And we have no way to set that when redirecting to the file.

So, you need to [enable stream mode](https://github.com/Rudloff/alltube/blob/master/resources/FAQ.md#enable-streaming-videos-through-the-server).
(You might need the fix in adba68edbc17f327ca04c5f23e3e0e2dfefa1733 in order to enable it properly though.)

**Comment by Mennaruuk** [comment]
I tried downloading from the site. It seems to be working presently. Now, it does save the video file as an FLV file, but I managed to rename the file extension into MP4, and the video successfully played.
