### ISSUE TITLE
 syntax error after upgrade to the latest docker version

### ISSUE THREAD

**Issue by Zyplonox** [Rudloff/alltube#251]
Hi, 

after i upgraded to the latest docker version i get folowing error: 

`Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/classes/LocaleManager.php on line 45`

regards

**Comment by Rudloff** [comment]
Hello,

Thanks for the report!
That's because the Docker image was still using PHP 7.0 and AllTube 2.1 now requires at least PHP 7.1.
It should now be fixed on the develop branch: https://hub.docker.com/layers/rudloff/alltube/develop/images/sha256-5af2b4b1a14cce9c69f666cd0f64a1de921100aa1bc3a551a116fd05363843ee

However, I don't use Docker myself anymore so the image is not well maintained.
It would be great if someone else could take care of it.

**Comment by Rudloff** [comment]
@Zyplonox Could you try the updated image?
