### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by SphinxTwo** [Rudloff/alltube#47]
After configuring the config files to work on Windows, I ran `npm install` & `composer install`, however, As for npm install, I get this error

![alt text](http://i.thebeast.tech/1458077814.png "npm install")

[Here's the log file if you need it.](http://bin.thebeast.tech/L4vAUwNyEQ)

Edit:
I restarted my computer and it loads up, now I have a problem with getting the download to work.

**Comment by Rudloff** [comment]
The npm install script was using Unix paths so it was not compatible with Windows. It should work now (https://github.com/Rudloff/alltube/commit/b2e29a8ab439cc49acd606310139b9333cce5bef).

In order to make the downloads work, you probably need to tweak the paths in config.yml.
(If it still does not work, please provide your Apache error log and any error printed by Alltube.)

**Comment by SphinxTwo** [comment]
Just ran `npm install` with the new package,json file, it installed fine. Now it's (Alltube) giving me an error 404 when I am trying to download/convert a link. I am using Nginx for my web server. There doesn't seem to be an error output.

**Comment by Rudloff** [comment]
I don't know much about Nginx but I guess you get 404 errors because AllTube uses some URL rewriting in .htaccess and Nginx does not read this file.
You probably need to add something like this to your Nginx configuration:
```
try_files $uri /index.php;
```
(AllTube uses the Slim framework so you can read about this here: http://docs.slimframework.com/routing/rewrite/#nginx)

Another solution would be to add a setting in config.yml that disables URL rewriting.

**Comment by SphinxTwo** [comment]
Alright. I will check try this out and report back.

**Comment by SphinxTwo** [comment]
Doesn't seem to work properly, would you like to take a look and see if I missed something?

**Comment by folta** [comment]
I added an example nginx config that works for me here: [https://github.com/Rudloff/alltube/issues/48](issue)

**Comment by SphinxTwo** [comment]
Seems like @folta 's config worked. I had to make a sub-domain for my version of Alltube which is

    server {
        server_name u.thebeast.tech;
        listen 80;

        root www/Alltube;
        index index.php;

        access_log  logs/alltube.access.log;
        error_log   logs/alltube.error.log;

        types {
                text/html   html htm shtml;
                text/css    css;
                text/xml    xml;
                application/x-web-app-manifest+json   webapp;
        }

        # Deny access to dotfiles
        location ~ /\. {
                deny all;
        }

        location / {
                try_files $uri /index.php?$args;
        }

        location ~ \.php$ {
                try_files $uri /index.php?$args;

                fastcgi_param     PATH_INFO $fastcgi_path_info;
                fastcgi_param     PATH_TRANSLATED $document_root$fastcgi_path_info;
                fastcgi_param     SCRIPT_FILENAME $document_root$fastcgi_script_name;

                fastcgi_pass php;
                fastcgi_index index.php;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_intercept_errors off;


                include fastcgi_params;
        }
    }
