### ISSUE TITLE
Feature request: playlists

### ISSUE THREAD

**Issue by TimoVerbrugghe** [Rudloff/alltube#58]
Hi Rudloff!

I'm trying to download a Youtube playlist, more specifically [this](https://www.youtube.com/playlist?list=PL2JiZAV5BmDXiLQ8I-pIG58ykUL6ee71Z) one (have also tried with others) but both on my selfhosted server as on your website I'm not getting the desired result.

On my own web server, alltube gives an error (see screenshot & pastebin for full error) that I need to check the URL of my video (which I did).

On your website, the first video, together with download option, comes up correctly. But when I click the download button, the video starts playing inside my browser (Chrome), instead of being downloaded.

Any settings that I need to adjust?

http://pastebin.com/xZA2mqUs (full error displayed)

![alltube1](https://cloud.githubusercontent.com/assets/7707120/16118858/2dd7529a-33d9-11e6-97da-4e3dbc94daba.PNG)

**Comment by Rudloff** [comment]
Hello,

Alltube is not designed to download playlists, it will always get only the first video.
It would be possible to add support for playlists but it would need some UI changes and I don't have the time right now. (But I am willing to accept a pull request.)

Chrome is playing the video because it is in a format it can play. You can download it simply by using ctrl + s or File > Save as.

What version are you using on your server? The latest [release](https://github.com/Rudloff/alltube/releases/tag/0.4.5) is quite older than the version running on alltubedownload.net so this is probably why you're getting a different behavior.

**Comment by TimoVerbrugghe** [comment]
Oh ok, that's why I get this behaviour. Thanks for the explanation!

Is the build that you're running on alltubedownload.net the same as building the source code from the master branch?

**Comment by Rudloff** [comment]
No, it uses the develop branch.

**Comment by hukoeth** [comment]
Hi,
I started working on this (https://github.com/hukoeth/alltube/tree/develop) but I've run into a couple of problems. Here's what I've done so far:   
- If you enter a playlist, you will be presented with a list of the videos and their download links   

Here's where I struggle:
- If the list is very large you will run into a timeout eventually unless you set the timeout to an impractically high value -> Some sort of progress on loading the information would be required but I'm not sure what the best way is to do that
- Currently the videos can only be downloaded one by one -> Again: not sure what the best way to solve this would be
- I can't test the casting feature since I don't have a device that supports google cast
- I only tested with Youtube so far

Since I have limited experience maybe someone else would like to help out with this (or give me some ideas how to implement some of the missing stuff)?
Thanks

**Comment by Rudloff** [comment]
Thanks a lot for working on this @hukoeth!

I've opened a PR so I can add comments to your code: https://github.com/Rudloff/alltube/pull/96

Also don't worry about Google cast support, we can add it later.

**Comment by Rudloff** [comment]
We now have basic playlist support on the `feature/playlist` branch.
I still need to test it with different websites and make it look a little better.
