### ISSUE TITLE
[Help] there is no file extension when i try to download . mp3 file

### ISSUE THREAD

**Issue by yas9999** [Rudloff/alltube#65]
Hello @Rudloff ,
i wan't to create an android webview with file manager, this file manager have allowed format (mp3,mp4,avi ....) if the download link doesn't contain the extension so there is no download
there is any possibility to change URL structure in order to provide mp3 extension !
for video download there is no problem at all because all links have there own extension

Best regards,

**Comment by Rudloff** [comment]
Hello,
On the Web, the content type is not determined by the extension but by the `Content-Type` HTTP header.
Alltube already returns `Content-Type: audio/mpeg` for MP3 files so there is no point changing the URL.

Moreover, if your web engine correctly uses the `Content-Disposition` header, it should already rename the file to `.mp3` because Alltube always returns this header when converting to audio:
```http
Content-Disposition: attachment; filename="Major Lazer & DJ Snake - Lean On (feat. MØ) (Official Music Video)-YqeW9_5kURI.mp3"
```

If the webview does not correctly detect the content type or the filename, I would suggest this is a bug with Android's webview component and not something to fix in Alltube.
If you can reproduce the issue with another browser, please reopen the issue.
