### ISSUE TITLE
en windows sale un error al momento de descargar la libreria ffmpeg

### ISSUE THREAD

**Issue by jorelpoder** [Rudloff/alltube#82]
help

  [RuntimeException]
  Failed to clone https://github.com/rg3/youtube-dl.git, git was not found, c
  heck that it is installed and in your PATH env.
  "git" no se reconoce como un comando interno o externo,
  programa o archivo por lotes ejecutable.

**Comment by Rudloff** [comment]
Like the message says, you need to have Git installed.
However I updated the develop branch so that it can now install youtube-dl from a tarball.

Note that you can also:
* Use a [release package](https://github.com/Rudloff/alltube/releases)
* Use `composer install --no-dev` and download youtube-dl manually

**Comment by jorelpoder** [comment]
lo siento el error es el siguiente 


  [RuntimeException]
  Failed to execute tar -xJf "C:\wamp\www\alltube\vendor/ffmpeg/ffmpeg/ffmpeg
  -release-64bit-static.tar.xz" -C "C:\wamp\www\alltube/vendor/composer/ed0aa
  0e9"
  "tar" no se reconoce como un comando interno o externo,
  programa o archivo por lotes ejecutable.


 soy estudiante de ingenieria de sistemas y aun no soy experto 
nota: estoy haciendo un mini proyecto y necesito descargar el audio en (windows)

**Comment by Rudloff** [comment]
You need [Tar](https://www.gnu.org/software/tar/) in order to extract the FFmpeg binary. But it won't be useful to you as it is a Linux binary.
Again, I recommend you use a release package (and get FFmpeg from elsewhere).

(If you only need to download some audio files, why don't you use https://www.alltubedownload.net/ or [youtube-dl](http://rg3.github.io/youtube-dl/)?)

**Comment by Rudloff** [comment]
No news for a month, I'm closing.
